name: pafee_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: 
  flutter_riverpod: 
  flutter_hooks:
  google_fonts: 
  go_router: 
  riverpod_annotation:
  flutter_local_notifications:
dev_dependencies:
  flutter_test:
    sdk: flutter
  hooks_riverpod:
  flutter_lints:
  riverpod_generator:
  build_runner:
  flutter_launcher_icons:
flutter_icons:       
  android: true
  ios: true
  image_path: "lib/images/pafee_icon.png"
flutter:
  uses-material-design: true
  assets:
     - lib/images/pafee.png
     - lib/images/pafee_icon.png
  
